name: wallet_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  provider: ^3.1.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.3+4
  json_annotation: ^3.0.0
  http: ^0.12.0+2
  protobuf: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  barcode_scan: ^1.0.0
  qr_flutter: ^2.1.0+55
  pull_to_refresh: ^1.5.6
  web_socket_channel_shared:
    git:
      url: git://github.com/imerkle/web_socket_channel.git
  universal_io: ^0.8.4
  plugfox_localstorage: ^0.1.1+1
  bip39: ^1.0.3
  protoc_plugin: ^19.0.1
  timeago:
    git:
      url: git://github.com/imerkle/timeago.dart.git
  after_init: ^0.1.2
  grpc: ^2.1.3
  js: ^0.6.0
  universal_html: ^1.2.1
  flutter_inner_drawer:
    git:
      url: git://github.com/imerkle/flutter_inner_drawer.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  mobx_codegen: ^1.1.0
  json_serializable: ^3.2.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lang/en.json
    - lang/sk.json
