// Automaticaly generated by rust_swig
package com.example.wallet_flutter;
import android.support.annotation.NonNull;

public final class C {

    public C()  {

        mNativeObj = init();
    }
    private static native long init() ;

    public static native String get_seed(@NonNull String a0, @NonNull String a1) ;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ long mNativeObj;
}