// Automaticaly generated by rust_swig
package com.example.wallet_flutter;


public final class C {

    public C(String a0)  {

        mNativeObj = init(a0);
    }
    private static native long init(String a0) ;

    public final String private_key()  {

        return do_private_key(mNativeObj);
    }
    private static native String do_private_key(long me) ;

    public final String public_key()  {

        return do_public_key(mNativeObj);
    }
    private static native String do_public_key(long me) ;

    public static native C [] get_wallets(String a0) ;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ long mNativeObj;
}